### PR TITLE
Zl dev

### PR DESCRIPTION
**Pull request by Zoe-creator**
fixed conflicts

### CODE REVIEW

**Review by brittanyowen — CHANGES_REQUESTED** [review]
can you change the "My WishList" header to an h3 tag so it can be styled like all the other headers on our site? thanks!

**Review by brittanyowen — CHANGES_REQUESTED** [review]
can you change the "My WishList" header to an h3 tag so it can be styled like all the other headers on our site? thanks!

**Review by ginestah — APPROVED** [review]
thank you

**Review by brittanyowen — APPROVED** [review]
perfect! Thank you!

**Pull request merged**
